using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BovespaData.DataClass.Entidade.BDI
{
    public class MaiorOscilacaoVistaState : Base.OscilaBase
    {
        //01 -TIPREG -TIPO DE REGISTRO FIXO "04" N(02) 01 02
        //02 -INDOSC -INDICA SE É OSCILAÇÃO POSITIVA OU NEGATIVA "A" = ALTA (POSITIVA) "B" = BAIXA (NEGATIVA) X(01) 03 03 
        //03 -NOMRES -NOME RESUMIDO DA EMPRESA EMISSORA DO PAPEL X(12) 04 15
        //04 -ESPECI -ESPECIFICAÇÃO DO PAPEL PARA PAPÉIS PERTENCENTES AO NOVO MERCADO, NAS POSIÇÕES 9 E 10 ESTÁ INDICADO: N1, N2 OU NM. X(10) 16 25
        //05 -PREULT -PREÇO DO ÚLTIMO NEGÓCIO EFETUADO COM PAPEL-MERCADO DURANTE O PREGÃO CORRENTE N(09)V99 26 36
        //06 -TOTNEG -NÚMERO DE NEGÓCIOS EFETUADOS COM O PAPEL-MERCADO NO PREGÃO CORRENTE N(05) 37 41
        //07 -OSCPRE -OSCILAÇÃO DO PREÇO DO PAPEL-MERCADO EM RELAÇÃO AO PREGÃO ANTERIOR N(03)V99 42 46
        //08 – CODMEG – CÓDIGO DE NEGOCIAÇÃO X(12) 47 58
        //09 – OSCILA -OSCILAÇÃO DO PREÇO DO PAPEL-MERCADO EM RELAÇÃO AO PREGÃO ANTERIOR N(05)V99 59 65
        //10 -RESERVA EM BRANCO X(285) 66 350
        public string Reserva { get; set; }
    }
}
