/*


ALTER TABLE TB_Feed ADD CONSTRAINT FK_Feed_FeedType FOREIGN KEY (FeedTypeId) REFERENCES TB_FeedType(FeedTypeId);
ALTER TABLE TB_Feed DROP CONSTRAINT FK_Feed_FeedType

ALTER TABLE TB_FeedKeyValue ADD CONSTRAINT FK_KeyValue_FeedId FOREIGN KEY (FeedId) REFERENCES TB_Feed(FeedId);


ALTER TABLE TB_FeedTransformation ADD CONSTRAINT FK_Trans_FeedId FOREIGN KEY (FeedId) REFERENCES TB_Feed(FeedId);


ALTER TABLE TB_FeedFilter ADD CONSTRAINT FK_Filter_FeedId FOREIGN KEY (FeedId) REFERENCES TB_Feed(FeedId);

ALTER TABLE TB_FeedTypeDefaultKeys ADD CONSTRAINT FK_FeedTypeDefaulKeys FOREIGN KEY (FeedTypeId) REFERENCES TB_FeedType(FeedTypeId);
ALTER TABLE TB_FeedTypeDefaultKeys DROP CONSTRAINT FK_FeedTypeDefaulKeys;
*/

